### PR TITLE
fix yml files with yamllint and change README

### PR DESCRIPTION
**Pull request by inktrap**
I made some changes that make it easier to get sloth-ci running. Also I had to create the docs from sdocs not docs:

```
 $ poetry run sphinx-build sdocs docs/_build/html
 ```

### CODE REVIEW

**Comment by inktrap** [comment]
In addition, all the commands are listed as, e.g.:
```
sci create timestamper.yml
```

But we are using poetry, so it is:

```
poetry run sci create timestamper.yml
```

**Comment by inktrap** [comment]
Regarding to line endings and yaml files … Perhaps you want to consider running everything through ``dos2unix`` and to change your IDE to use ``\n`` … I know it is your project and your OS … I hope I am not impolite here but I thought it wont hurt to ask; this is the first and only project I found on GH or Bitbucket that uses windows conventions (e.g. ``\n\r``).

For yaml I would use ``yamllint`` and for python ``black``.

**Comment by inktrap** [comment]
Also ``sloth_ci.ext.devtools`` should be part of the dev dependencies, right?

```
poetry add sloth_ci.ext.devtools --dev
```

**Comment by inktrap** [comment]
If I install it as a dev dependency and run it to write a validator:

```
poetry run sci dev -v webhook
```

I sadly get:

```
Could not load extension dev: No module named 'sloth_ci.ext.devtools'
```

But poetry says that it is installed (``--dry-run``):

```
  • Installing sloth-ci.ext.devtools (1.0.4): Skipped for the following reason: Already installed
```

and even without.

**Comment by inktrap** [comment]
So please see them as suggestions. Without feedback I would not run yamllint, even running dos2unix and black are … your decisions to make, not mine.

When the devtools work I would like to write a guide how to write a validator, while writing one. :)

**Comment by moigagoo** [comment]
Hi! First of all, thanks a lot for your interest in Sloth CI and for your contribution. 

I have to decline the PR for now because I'm migrating the docs from Sphinx to Foliant so contributions to the old Sphinx-based docs (currently found in sdocs) are irrelevant.

I know it's my fault that I didn't pronounce my plans wrt the docs in the README well enough and I'm really sorry I'll have to not use your work right now. However, I hope you won't be discouraged to contribute to the project later.

My plans currently are:
- migrate from Sphinx to Foliant (in progress)
- migrate to Poetry (mostly done, only the dev deps and namespace stories aren't conplete)
- deprecate most of the extensions to lower the support surface; most of them won't work now anyway (haven't started yet).

**Comment by inktrap** [comment]
Ah, don't worry, I just made some changes that I thought to be useful, but if they don't fit the direction of the project it's fine.
I guess some contribution guidelines and a roadmap would be useful if you want interested developers to help out. If I can do something to help, just let me know.

Personally I would like to have some simple validator for arbitrary git repos with a [notify-webhook](https://github.com/metajack/notify-webhook) which is similar to the GitHub Validator that already exists.

Btw.minor detail: [GitHub discourages IP-checks](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/about-githubs-ip-addresses):

>  We do not recommend allowing by IP address, however if you use these IP ranges we strongly encourage regular monitoring of our API.

 but the validators checks a range ([``    trusted_ips = ip_network('192.30.252.0/22')``](https://github.com/Sloth-CI/sloth-ci-validators/blob/master/github/github.py#L60)) so it might be fine.

**Pull request closed without merging**
